version: '3.8'

services:

  # -------------------- NGINX API Gateway --------------------
  nginx:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - auth
      - cart
      - product
      - order
      - payment
      - email
      - seller-dashboard
      - aibuddy

  # -------------------- Auth Service --------------------
  auth:
    image: ashutoshnigam300/auth-service:latest
    container_name: auth
    build:
      context: .
      dockerfile: authService/Dockerfile
    ports:
      - "8081:8081"

  # -------------------- Cart Service --------------------
  cart:
    image: ashutoshnigam300/cart-service:latest
    container_name: cart
    build:
      context: .
      dockerfile: cartService/Dockerfile
    ports:
      - "8082:8082"

  # -------------------- Product Service --------------------
  product:
    image: ashutoshnigam300/product-service:latest
    container_name: product
    build:
      context: .
      dockerfile: productService/Dockerfile
    ports:
      - "8083:8083"

  # -------------------- Order Service --------------------
  order:
    image: ashutoshnigam300/order-service:latest
    container_name: order
    build:
      context: .
      dockerfile: orderService/Dockerfile
    ports:
      - "8084:8084"

  # -------------------- Payment Service --------------------
  payment:
    image: ashutoshnigam300/payment-service:latest
    container_name: payment
    build:
      context: .
      dockerfile: paymentService/Dockerfile
    ports:
      - "8085:8085"

  # -------------------- AI Buddy Service --------------------
  aibuddy:
    image: ashutoshnigam300/aibuddy-service:latest
    container_name: aibuddy
    build:
      context: .
      dockerfile: aibuddyService/Dockerfile
    ports:
      - "8086:8086"

  # -------------------- Email Service --------------------
  email:
    image: ashutoshnigam300/email-service:latest
    container_name: email
    build:
      context: .
      dockerfile: emailService/Dockerfile
    ports:
      - "8087:8087"

  # -------------------- Seller Dashboard Service --------------------
  seller-dashboard:
    image: ashutoshnigam300/seller-dashboard-service:latest
    container_name: seller-dashboard
    build:
      context: .
      dockerfile: sellerDashboardService/Dockerfile
    ports:
      - "8088:8088"
