# ===================== Auth Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ashutoshnigam300/auth-service:latest
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30081

# ===================== Cart Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: ashutoshnigam300/cart-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    app: cart
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
      nodePort: 30082

# ===================== Product Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: ashutoshnigam300/product-service:latest
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 30083

# ===================== Order Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ashutoshnigam300/order-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084

# ===================== Payment Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: ashutoshnigam300/payment-service:latest
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085



# ===================== Email Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: ashutoshnigam300/email-service:latest
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30087

# ===================== Seller Dashboard Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seller-dashboard-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seller-dashboard
  template:
    metadata:
      labels:
        app: seller-dashboard
    spec:
      containers:
        - name: seller-dashboard
          image: ashutoshnigam300/seller-dashboard-service:latest
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: seller-dashboard
spec:
  selector:
    app: seller-dashboard
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
      nodePort: 30088
