# ===================== Monolith Deployment & Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: ashutoshnigam300/monolith:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monolith
spec:
  selector:
    app: monolith
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080       # Internal cluster port
      targetPort: 8080 # Container port
      nodePort: 30080  # Exposed externally

# ===================== AI Buddy Service Deployment & Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibuddy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aibuddy
  template:
    metadata:
      labels:
        app: aibuddy
    spec:
      containers:
        - name: aibuddy
          image: ashutoshnigam300/aibuddy-service:latest
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: aibuddy
spec:
  selector:
    app: aibuddy
  type: NodePort
  ports:
    - protocol: TCP
      port: 8086       # Internal cluster port
      targetPort: 8086 # Container port
      nodePort: 30086  # Exposed externally
