apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-k8s
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-scaling
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments/scale"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-scaling
  namespace: default
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: default
roleRef:
  kind: Role
  name: prometheus-scaling
  apiGroup: rbac.authorization.k8s.io