apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: default
  labels:
    release: prometheus-stack
spec:
  route:
    receiver: default
    routes:
      - matchers:
          - name: alertname
            value: MonolithHighLatency
        receiver: scale-up

      - matchers:
          - name: alertname
            value: ServiceLowTraffic
        receiver: scale-down

  receivers:
    - name: scale-up
      webhookConfigs:
        - url: "http://alert-webhook.default.svc:8080/scale-up"

    - name: scale-down
      webhookConfigs:
        - url: "http://alert-webhook.default.svc:8080/scale-down"

    - name: default
      webhookConfigs:
        - url: "http://alert-webhook.default.svc:8080/alert"