apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monolith-servicemonitor
  namespace: default
  labels:
    release: prometheus-stack   # ✅ FIXED
spec:
  selector:
    matchLabels:
      app: monolith
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http