# ===================== Email Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: ashutoshnigam300/email-service:latest
          ports:
            - containerPort: 8087
---
apiVersion: v1
kind: Service
metadata:
  name: email
spec:
  type: NodePort
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 8087
      targetPort: 8087
      nodePort: 30087