# ===================== Monolith Deployment & Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monolith-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monolith
  template:
    metadata:
      labels:
        app: monolith
    spec:
      containers:
        - name: monolith
          image: ashutoshnigam300/monolith:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: monolith-service
  labels:
    app: monolith
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: monolith
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080        # Internal cluster port
      targetPort: 8080  # Container port
      nodePort: 30080

