
# ===================== Order Service =====================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: ashutoshnigam300/order-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 30084